cutoff/Controllers/ProfileController.cs
using System;
using cutoff.Helpers;
using cutoff.Models;
using Microsoft.AspNetCore.Mvc;

namespace cutoff.Controllers
{
	public class ProfileController : Controller
	{
        private readonly DataAccessor _dataAccessor;

        public ProfileController(DataAccessor dataAccessor)
        {
            _dataAccessor = dataAccessor;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserName") != null)
            {
                string userName = HttpContext.Session.GetString("UserName") ?? "";
                UserDTO user = _dataAccessor.GetUsers().Where(u => u.UserName == userName).FirstOrDefault();
                UserVM profile = new UserVM
                {
                    UserEmail = user.UserEmail,
                    UserFirst = user.UserFirst,
                    UserLast = user.UserLast,
                    UserName = user.UserName,
                    UserPassword = user.UserPassword
                };
                return View(profile);
            }
            return RedirectToAction("Index", "Authorization");
        }
    }
}

cutoff/Controllers/ShowController.cs
using System;
using cutoff.Helpers;
using cutoff.Models;
using cutoff.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;

namespace cutoff.Controllers;

public class ShowController : Controller
{
    private readonly DataAccessor _dataAccessor;
    private readonly ShowService _showService;
    private readonly NetworkService _networkService;
    private readonly GenreService _genreService;
    private readonly LanguageService _languageService;

    public ShowController(DataAccessor dataAccessor, ShowService showService, NetworkService networkService, GenreService genreService, LanguageService languageService)
    {
        _dataAccessor = dataAccessor;
        _showService = showService;
        _networkService = networkService;
        _genreService = genreService;
        _languageService = languageService;
    }

    public IActionResult Index()
    {
        if (HttpContext.Session.GetString("UserName") != null)
        {
            string userName = HttpContext.Session.GetString("UserName") ?? "";
            var model = new ShowIndexVM(_dataAccessor, _networkService, _genreService, _languageService, userName);
            return View(model);
        }
        return RedirectToAction("Index", "Authorization");
    }

    public IActionResult ShowGrid(int networkId, int genreId, int languageId)
    {
        if (HttpContext.Session.GetString("UserName") != null)
        {
            string userName = HttpContext.Session.GetString("UserName") ?? "";
            var model = new ShowGridVM(_dataAccessor, _showService, userName, networkId, genreId, languageId);
            return PartialView("ShowGridPartial", model);
        }
        return RedirectToAction("Index", "Authorization");
    }

    public IActionResult ShowModal(int showId)
    {
        if (HttpContext.Session.GetString("UserName") != null)
        {
            string userName = HttpContext.Session.GetString("UserName") ?? "";
            var model = new ShowModalVM(_dataAccessor, _showService, userName, showId);
            return View("ShowModalPartial", model);
        }
        return RedirectToAction("Index", "Authorization");
    }

    [HttpPost]
    public void ToggleShow(int showId)
    {
        if (HttpContext.Session.GetString("UserName") != null)
        {
            string userName = HttpContext.Session.GetString("UserName") ?? "";
            _showService.ToggleShow(userName, showId);
        }
    }

    [HttpPost]
    public void ToggleShowEpisode(int showId, int seasonNumber, int episodeNumber)
    {
        if (HttpContext.Session.GetString("UserName") != null)
        {
            string userName = HttpContext.Session.GetString("UserName") ?? "";
            _showService.ToggleShowEpisode(userName, showId, seasonNumber, episodeNumber);
        }
    }
}

cutoff/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Session;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cutoff</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cutoff.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-light navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cutoff</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Show" asp-action="Index">Shows</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Movie">Movies</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button class="btn btn-outline-primary" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - cutoff - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>